run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    #- gocyclo response wrapper for server handler is too complex
    - gofmt
    - golint
    - govet
    - ineffassign
    #- interfacer
    - lll
    - misspell
    - nakedret
    - unparam
    # Replaces structcheck and varcheck. Available since go 1.20
    - unused

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0.85
