# This is the default config that is being provided along with the collector
# image.

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  zipkin:

processors:
  batch:

exporters:
  kafka:
    protocol_version: 2.0.0
    brokers:
      - ${EXPORTER_KAFKA_BROKER}
    topic: ${EXPORTER_KAFKA_TOPIC}
    encoding: jaeger_proto
    compression:
      codec: gzip
      level: 5

service:
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [kafka]

  extensions: [health_check, pprof, zpages]
