name: Publish artifacts
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-docker-main-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PUBLISH_USER }}
          password: ${{ secrets.DOCKERHUB_PUBLISH_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: hypertrace/hypertrace-collector:main
          build-args: |
            VERSION=latest
            GIT_COMMIT=${GITHUB_SHA}
